.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH drbd-overview 1 "November 7, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
drbd-overview \- Overview of all configured DRBD resources
.SH SYNOPSIS
.B drbd-overview
.SH DESCRIPTION
.PP
drbd-overview offers an overview of the state of all configured DRBD resources.
It provides information about the connection status of each DRBD resource. It
will also use auxiliary information provided by \fBdf\fR(1), \fBlvm\fR(8),
\fBxm\fR(1) and \fBvirsh\fR(1) for DRBD resources used as mounted filesystems,
LVM physical volumes, Xen domain backing disks and libvirt instance disks
respectively.

.SH AUTHOR
.PP
drbd-overview was written by Philipp Reisner <philipp.reisner@linbit.com> and
Lars Ellenberg <lars.ellenberg@linbit.com>.

This manual page was written by Apollon Oikonomopoulos <apoikos@gmail.com> for the Debian project (but may be used by others).

.SH COPYRIGHT
.PP
Copyright 2001-2013 LINBIT Information Technologies, Philipp Reisner, Lars
Ellenberg. This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

.SH SEE ALSO
\fBdrbdadm\fP(8), \fBdrbdsetup\fP(8)
